# -------- Dev Stage --------
  FROM node:lts-alpine

  WORKDIR /usr/src/app
  RUN corepack enable
  
  # Copy dependency manifests
  COPY package.json yarn.lock eslint.config.mjs nx.json tsconfig.base.json ./
  
  # Install all dependencies (dev + prod)
  RUN yarn config set nodeLinker node-modules
  RUN yarn install
  
  # Copy sources (but we’ll still mount them in volumes)
  COPY libs ./libs
  COPY apps ./apps
  COPY packages ./packages
  
  # Default: run NX serve for a service (override in docker-compose)
  CMD ["yarn", "nx", "serve", "api-gateway", "--verbose", "--hmr"]