services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVICE: api-gateway
    volumes:
      - ./apps/api-gateway:/usr/src/app/apps/api-gateway
      - ./libs:/usr/src/app/libs
      - ./packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    command: yarn nx serve api-gateway --verbose --hmr
    ports:
      - '8080:8080'
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
    networks:
      - microservice-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVICE: user-service
    volumes:
      - ./apps/user-service:/usr/src/app/apps/user-service
      - ./libs:/usr/src/app/libs
      - ./packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    command: yarn nx serve user-service --verbose --hmr
    ports:
      - '8081:8081'
      - '50051:50051'
    environment:
      - USER_SERVICE_PORT=${USER_SERVICE_PORT}
    networks:
      - microservice-network

  product-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVICE: product-service
    volumes:
      - ./apps/product-service:/usr/src/app/apps/product-service
      - ./libs:/usr/src/app/libs
      - ./packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    command: yarn nx serve product-service --verbose --hmr
    ports:
      - '8082:8082'
      - '50052:50052'
    environment:
      - PRODUCT_SERVICE_PORT=${PRODUCT_SERVICE_PORT}
    networks:
      - microservice-network

  logger-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        SERVICE: logger-service
    volumes:
      - ./apps/logger-service:/usr/src/app/apps/logger-service
      - ./libs:/usr/src/app/libs
      - ./packages:/usr/src/app/packages
      - /usr/src/app/node_modules
    command: yarn nx serve logger-service --verbose --hmr
    ports:
      - '8083:8083'
    environment:
      - LOGGER_SERVICE_PORT=${LOGGER_SERVICE_PORT}
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
